language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - pip install -U pip wheel
  - pip install setuptools==24.0.3
  - pip install -r requirements.txt
  - python setup.py -q install
# command to run tests
script:
  - python setup.py test
  - pywind decc_extract
