language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - pip install -U pip wheel
  - pip install setuptools==24.0.3
  - pip install -r requirements.txt
# command to run tests
script:
  - bundle exec python setup.py install
  - bundle exec pywind decc_extract
